=== 5u623l20/freebsd-doc/share/sgml/press.dtd
<!-- $FreeBSD$ -->

<!ELEMENT press (cvs:keyword?, year)+>

<!ELEMENT year (name, (month)+)>
<!ATTLIST year
  id		ID	#IMPLIED
>

<!ELEMENT month (name, (story)+)>
<!ATTLIST month
  id		ID	#IMPLIED
>

<!ELEMENT story (name, url, site-name, site-url, date, author, (p)+)>
<!ATTLIST storyevent
  id		ID	#IMPLIED
>

<!ELEMENT name (#PCDATA)>
<!ATTLIST name
  id		ID	#IMPLIED
>
<!ELEMENT url (#PCDATA)>
<!ATTLIST url
  id		ID	#IMPLIED
>
<!ELEMENT site-name (#PCDATA)>
<!ATTLIST site-name
  id		ID	#IMPLIED
>
<!ELEMENT site-url (#PCDATA)>
<!ATTLIST site-url
  id		ID	#IMPLIED
>
<!ELEMENT date (#PCDATA)>
<!ATTLIST date
  id		ID	#IMPLIED
>
<!ELEMENT author (#PCDATA)>
<!ATTLIST author
  id		ID	#IMPLIED
>

<!ELEMENT p (#PCDATA | a | tt)*>
<!ATTLIST p
  id		ID	#IMPLIED
>

<!ELEMENT tt (#PCDATA)>
<!ATTLIST tt
  id		ID	#IMPLIED
>

<!ELEMENT a (#PCDATA)>
<!ATTLIST a
  id		ID	#IMPLIED
  href		CDATA	#REQUIRED
>

<!ENTITY % cvs
 PUBLIC "-//FreeBSD//DTD FreeBSD CVS Keywords//EN"
	"http://www.FreeBSD.org/XML/doc/share/sgml/cvs.dtd">
%cvs;

<!ENTITY % autogen.ent
 PUBLIC "-//FreeBSD//ENTITIES FreeBSD Automatically Generated Entities//EN"
        "http://www.FreeBSD.org/XML/cwd/autogen.ent">
%autogen.ent;

<!ENTITY % iso8879.ent
 PUBLIC "-//FreeBSD//ENTITIES ISO 8879:1986 Entity Set//EN//XML"
        "http://www.FreeBSD.org/XML/www/share/sgml/iso8879.ent">
%iso8879.ent;

<!ENTITY % l10n.ent
 PUBLIC "-//FreeBSD//ENTITIES FreeBSD L10N Entities//EN"
        "http://www.FreeBSD.org/XML/www/lang/share/sgml/l10n.ent">
%l10n.ent;

<!ENTITY % l10n-common.ent
 PUBLIC "-//FreeBSD//ENTITIES FreeBSD L10N Common Entities//EN"
        "http://www.FreeBSD.org/XML/www/share/sgml/l10n.ent">
%l10n-common.ent;

<!ENTITY % common.ent
 PUBLIC "-//FreeBSD//ENTITIES FreeBSD Common Entities//EN"
        "common.ent">
%common.ent;

=== 5u623l20/freebsd-doc/share/sgml/press.xml
<?xml version="1.0"?>
<!DOCTYPE press PUBLIC "-//FreeBSD//DTD FreeBSD XML Database for Press//EN"
                      "http://www.FreeBSD.org/XML/www/share/sgml/press.dtd">
<!--
 COMMITTERS PLEASE NOTE:
    News articles referenced in this file are also to be archived under
    "freefall:/c/www/bsddoc/press/".
-->
<press>
  <cvs:keywords xmlns:cvs="http://www.FreeBSD.org/XML/CVS" version="1.0">
    <cvs:keyword name="freebsd">
      $FreeBSD: www/share/sgml/press.xml,v 1.73 2009/01/14 04:25:43 jkoshy Exp $
    </cvs:keyword>
  </cvs:keywords>

  <year>
    <name>2009</name>

    <month>
      <name>1</name>
      <story>
	<name>Coyote Point Builds on FreeBSD to Accelerate</name>
	<url>http://www.internetnews.com/infra/article.php/3795791</url>
	<site-name>Internet News</site-name>
	<site-url>http://www.internetnews.com/</site-url>
	<date>13 January 2009</date>
	<author>Sean Michael Kerner</author>
	<p>FreeBSD is at the core of Coyote Point's appliance.</p>
      </story>

      <story>
	<name>FreeBSD 7.1 Gets a Little Help from Sun</name>
	<url>http://www.internetnews.com/dev-news/article.php/3794561</url>
	<site-name>Internet News</site-name>
	<site-url>http://www.internetnews.com/</site-url>
	<date>06 January 2009</date>
	<author>Sean Michael Kerner</author>
	<p>An article covering technology sharing between Sun and the FreeBSD
	  project and other new features in FreeBSD 7.1.</p>
      </story>
    </month>
  </year>

</press>

=== 5u623l20/freebsd-doc/de/share/sgml/press.xml
<?xml version="1.0"?>
<!DOCTYPE press PUBLIC "-//FreeBSD//DTD FreeBSD XML Database for Press//EN"
                      "http://www.FreeBSD.org/XML/www/share/sgml/press.dtd">
<!--
 COMMITTERS PLEASE NOTE:
    News articles referenced in this file are also to be archived under
    "freefall:/c/www/bsddoc/press/".
    $FreeBSDde: de-www/share/sgml/press.xml,v 1.54 2009/02/15 09:09:49 jkois Exp $
    basiert auf: 1.74
-->

<press>
  <cvs:keywords xmlns:cvs="http://www.FreeBSD.org/XML/CVS" version="1.0">
    <cvs:keyword name="freebsd">
      $FreeBSD$
    </cvs:keyword>
  </cvs:keywords>

  <year>
    <name>2009</name>

    <month>
      <name>1</name>

      <story>
        <name>Coyote Point Builds on FreeBSD to Accelerate</name>
        <url>http://www.internetnews.com/infra/article.php/3795791</url>
        <site-name>Internet News</site-name>
        <site-url>http://www.internetnews.com/</site-url>
        <date>13. Januar 2009</date>
        <author>Sean Michael Kerner</author>
        <p>FreeBSD bildet die Basis f&#252;r Coyote Point's Software
          zur Beschleunigung von Webapplikationen.</p>
      </story>

      <story>
        <name>FreeBSD 7.1 Gets a Little Help from Sun</name>
        <url>http://www.internetnews.com/dev-news/article.php/3794561</url>
        <site-name>Internet News</site-name>
        <site-url>http://www.internetnews.com/</site-url>
        <date>06. Januar 2009</date>
        <author>Sean Michael Kerner</author>
        <p>Ein Artikel, der den Technologietransfer zwischen FreeBSD
	  und Sun n&#228;her beschreibt und zus&#228;tzlich neue
	  Funktionalit&#228;ten von FreeBSD 7.1 vorstellt.</p>
      </story>
    </month>
  </year>
</press>
